### ISSUE TITLE
Updating state programatically

### ISSUE THREAD

**Issue by thevillavicencio** [keermanish/react-page-maker#3]
How can I update the state programatically? I want the payload props to change once I finish 'editing' a draggable component.

**Comment by keermanish** [comment]
I'm not sure whether I've followed your question correctly, but there is a way where you can update the payload of the dropped component.

If you see the documentation of `Dropzone` it has `onDrop` props where you will get the data (including payload) of the dropped component and a callback function. You just have to pass the new payload data to that callback function and it will update the state respectively.

**Comment by thevillavicencio** [comment]
Sorry for not elaborating that much. So, I'm using this package to create a page builder. The components that I want to drag and drop have editable properties controlled by props. Say, I have a carousel that needs image URLs. I sorted a way of adding an overlay where I show a form so that users can type in a list of URLs. Now, from there, how can I grab these URLs and pass them over to the state object? Notice that the onDrop event has happened already.

**Comment by keermanish** [comment]
Unfortunate there is no much support/API to update the state directly post element drop.

Maybe you try with `dangerouslySetElements` which is available under `Dropzone` component. Here you will get all the elements and its data which have been dropped (in your case it will be a slider) and then you can tweak the data as per your need.

In this case, you will call `dangerouslySetElements` once your URL form is submitted.

**Comment by keermanish** [comment]
make sure you pass a function to `dangerouslySetElements` that way you will access to dropped elements and its data.


```
onSomeAction = () => {
    // Note - make sure you are passign valid data, else state service may break
    const current = this.currentDropzone.current;
    current && current.dangerouslySetElements((currentElements) => currentElements
      .map(doSomeTweaks));
  }

  <Dropzone
    ref={this.currentDropzone}
    {...requiredProps}
  />
```

**Comment by keermanish** [comment]
the upcoming release will have this API's :) After some testing will push it on NPM.

https://github.com/keermanish/react-page-maker/pull/4

some new API's include
```
state.removeElement(elementID, dropzoneID, parentID, cb);
state.updateElement(elementID, dropzoneID, parentID, newData, cb);
```

**Comment by keermanish** [comment]
Added support for new state API's to manage the fields. Please use a new release and check the latest [Doc](https://github.com/keermanish/react-page-maker#state).

Closing this.
